
services:
  mermaider:
    build: .
    image: mermaider-mcp
    container_name: mermaider
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - PORT=3000
    cap_add:
      - SYS_ADMIN
    init: true
    volumes:
       - ./docker-config.json:/app/etc/docker.json:ro
    networks:
      - mcp-servers

networks:
  mcp-servers:
    external: true